### ISSUE TITLE
Elementor Pro 3.5.1 Breaks site ($menu.smartmenus is not a function)

### ISSUE THREAD

**Issue by TheCookieMonster70** [elementor/elementor#17043]
After updating to Elementor Pro 3.5.1 Site breaks with error: jQuery.Deferred exception: this.elements.$menu.smartmenus is not a function.

I've disabled all plugins minus Elementor & Elementor Pro. Even On fresh install.

Popups stop working and can not edit pages as Elementor will not load.

**Comment by jaysonwebtel** [comment]
I am having the same issue with different themes where the headers used to work but no longer work on Elementor Pro 3.5 or 3.6 subversions...   Also I noted that Smart Menu's is hopelessly out of date - V1.0.1 from 2016 when there newer versions as recent as 2020 that apparently fix JS errors according to the changelog that has not been incorporated in Elementor Pro Plugin.
