### ISSUE TITLE
🐞 Bug report: Controls_Manager::SELECT2 stopped working since version 3.7.0

### ISSUE THREAD

**Issue by DesignInvento** [elementor/elementor#19406]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi There,
Controls_Manager::SELECT2 stopped working since version 3.7.0 
if a widget has SELECT2 control, whole whole control panel will be crashed and no setting to display.  
https://nimb.ws/0gHPI9

### Steps to reproduce

1. SELECT2 control to any widget
2. add widget to a page in editor
3. update and refresh page
4. again select same widget, no settings will be displayed.
5. remove SELECT2 control editor control panel will start working.

### Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: WINNT
	Software: Apache/2.4.46 (Win64) OpenSSL/1.1.1g PHP/7.4.11
	MySQL version: mariadb.org binary distribution v10.4.14
	PHP Version: 7.4.11
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: http://localhost/wp/petclassified
	Home URL: http://localhost/wp/petclassified
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: help.designinvento@gmail.com
	Debug Mode: Active

== Theme ==
	Name: PetClassified
	Version: 1.0.0
	Author: Designinvento
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0

== Active Plugins ==
	AccessPress Social Login
		Version: 2.1.0
		Author: AccessPress Themes

	All-in-One WP Migration
		Version: 7.62
		Author: ServMask

	DirectoryPress
		Version: 3.4.5
		Author: DirectoryPress

	DirectoryPress Advanced Fields
		Version: 1.0.3
		Author: DirectoryPress

	DirectoryPress Claim Listing
		Version: 1.0.1
		Author: DirectoryPress

	DirectoryPress Extended Location
		Version: 1.7.1
		Author: DirectoryPress

	DirectoryPress Frontend Listing
		Version: 2.5.5
		Author: DirectoryPress

	DirectoryPress MultiDirectory
		Version: 2.8.1
		Author: DirectoryPress

	DirectoryPress Payment Manager
		Version: 2.9.2
		Author: DirectoryPress

	Elementor
		Version: 3.7.0
		Author: Elementor.com

	ElKit ( Elementor Addons Kit )
		Version: 1.0.0
		Author: Designinvento

	Form Builder WP
		Version: 1.0.0
		Author: Designinvento

	Frontend Messages For DirectoryPress
		Version: 5.4.1
		Author: Designinvento

	Header Footer Builder
		Version: 1.0.0
		Author: Designinvento

	Nextend Social Login
		Version: 3.1.5
		Author: Nextendweb

	PetClassified Core
		Version: 1.0.0
		Author: Designinvento

	WooCommerce
		Version: 6.7.0
		Author: Automattic

	WordPress Importer
		Version: 0.7
		Author: wordpressdotorg

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	
Log: showing 20 of 262022-06-29 13:16:27 [info] elementor::elementor_updater Started 
2022-06-29 13:16:27 [info] Elementor/Upgrades - _on_each_version Start  
2022-06-29 13:16:27 [info] Elementor/Upgrades - _on_each_version Finished 
2022-06-29 13:16:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.5',
  'to' => '3.6.6',
)]
2022-07-07 15:17:40 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-07 15:17:42 [info] elementor::elementor_updater Started 
2022-07-07 15:17:42 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-07 15:17:42 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-07 15:17:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-27 15:52:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-27 15:52:02 [info] elementor::elementor_updater Started 
2022-07-27 15:52:02 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-27 15:52:02 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-27 15:52:02 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-08 15:53:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-08 15:53:54 [info] elementor::elementor_updater Started 
2022-08-08 15:53:55 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-08 15:53:55 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-08 15:53:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-08 15:53:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]

PHP: showing 3 of 3PHP: 2022-04-27 23:19:18 [warning X 5][D:\work\xampp-new\htdocs\wp\petclassified\wp-content\plugins\elementor\includes\managers\controls.php::776] array_merge(): Expected parameter 2 to be an array, string given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-04-29 01:08:22 [warning X 1][D:\work\xampp-new\htdocs\wp\petclassified\wp-content\plugins\elementor\includes\managers\controls.php::776] array_merge(): Expected parameter 2 to be an array, int given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-05-11 11:14:28 [error X 2][D:\work\xampp-new\htdocs\wp\petclassified\wp-content\plugins\elementor\includes\managers\widgets.php::208] Uncaught TypeError: Argument 1 passed to Elementor\Widgets_Manager::register_widget_type() must be an instance of Elementor\Widget_Base, instance of Elementor\Pacz_Extend_Sticky given, called in D:\work\xampp-new\htdocs\wp\petclassified\wp-content\plugins\petclassified-core\includes\class-petclassified-core.php on line 99 and defined in D:\work\xampp-new\htdocs\wp\petclassified\wp-content\plugins\elementor\includes\managers\widgets.php:208
Stack trace:
#0 D:\work\xampp-new\htdocs\wp\petclassified\wp-content\plugins\petclassified-core\includes\class-petclassified-core.php(99): Elementor\Widgets_Manager->register_widget_type(Object(Elementor\Pacz_Extend_Sticky))
#1 D:\work\xampp-new\htdocs\wp\petclassified\wp-includes\class-wp-hook.php(307): PetClassified_Core->petclassified_register_elementor_widgets(Object(Elementor\Widgets_Manager))
#2 D:\work\xampp-new\htdocs\wp\petclassified\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#3 D:\work\xampp-new\htdocs\wp\petclassified\wp-includes\plug [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 13 of 13JS: 2022-04-28 00:04:19 [error X 1][http://localhost/wp/petclassified/wp-content/plugins/petclassified-core/assets/js/frontend.js:6:3] WidgethfbNavMenuHandler is not defined 
JS: 2022-05-10 10:39:16 [error X 5][http://localhost/wp/petclassified/wp-content/plugins/elementor/assets/js/editor.min.js:2:492992] W.match is not a function 
JS: 2022-05-11 14:59:56 [error X 1][http://localhost/wp/petclassified/wp-content/plugins/elkit/assets/js/elkit-public.js:54:4] getDocumentSettings is not defined 
JS: 2022-05-11 15:04:53 [error X 1][http://localhost/wp/petclassified/wp-content/plugins/elkit/assets/js/elkit-public.js:54:4] el.data.settings is undefined 
JS: 2022-05-11 15:14:28 [error X 1][http://localhost/wp/petclassified/wp-content/plugins/elkit/assets/js/elkit-public.js:51:24] obj is not defined 
JS: 2022-05-11 15:17:42 [error X 11][http://localhost/wp/petclassified/wp-content/plugins/elkit/assets/js/elkit-public.js:51:22] element_settings is undefined 
JS: 2022-05-11 15:36:59 [error X 3][http://localhost/wp/petclassified/wp-content/plugins/elkit/assets/js/elkit-public.js:52:28] inner_section_settings is undefined 
JS: 2022-05-11 15:40:37 [error X 1][http://localhost/wp/petclassified/wp-content/plugins/elkit/assets/js/elkit-public.js:51:36] el.child is not a function 
JS: 2022-06-30 20:14:15 [error X 3][http://localhost/wp/petclassified/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js:1:20425] this.placeholder is undefined 
JS: 2022-08-08 16:26:56 [error X 1][http://localhost/wp/petclassified/wp-content/plugins/elementor/assets/js/editor.min.js:3:731581] elementor.config.dev_tools is undefined 
JS: 2022-08-08 18:06:42 [error X 9][http://localhost/wp/petclassified/wp-content/plugins/elementor/assets/js/web-cli.min.js:3:134456] T.setRegisterConfig is not a function 
JS: 2022-08-08 20:45:09 [error X 10][http://localhost/wp/petclassified/wp-content/plugins/elementor/assets/js/editor.min.js:3:286320] elementorDevTools is not defined 
JS: 2022-08-08 22:01:28 [error X 4][http://localhost/wp/petclassified/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js:24:739] a is null 

== Elementor - Compatibility Tag ==
	
	ElKit ( Elementor Addons Kit ): Compatibility not specified

**Comment by DesignInvento** [comment]
Working fine with elementor 3.6.8

**Comment by momo-fr** [comment]
Hi, I try to update Elementor Free in last version but in more case the editor not open… :-((
I try to desactivate plugins, theme, PHP version (8.1 to 7.4) same issue.
Some websites have light environment others big configuration (25 plugins), the first not work and the second work fine!
If I downgrade to 6.6.8 everything works fine.
I'm completely lost with this version...

**Comment by Slapbox** [comment]
Same, or at least similar, issue. Can't open the editor in 3.7.0.

**Comment by momo-fr** [comment]
Big problem on a website all the contents of the pages have disappeared! Revisions are empty!

**Comment by Slapbox** [comment]
@momo-fr you should reach out to support.

**Comment by rami-elementor** [comment]
Hi @DesignInvento ,

I can't recreate the issue. Can you please try to test this in a clean website with only Elementor & Elementor Pro.

I see your System Info has many plugins. Maybe the issues is in one of your addons?

**Comment by momo-fr** [comment]
One thing comes to mind, the first sites I updated had the database update banner, then I didn't see it anymore, is that normal?
I have to update more than 100 websites.

**Comment by DesignInvento** [comment]
> Hi @DesignInvento ,
> 
> I can't recreate the issue. Can you please try to test this in a clean website with only Elementor & Elementor Pro.
> 
> I see your System Info has many plugins. Maybe the issues is in one of your addons?

yes i can confirm, issue resolved, it seems like a cache issue by restarting xampp i was able to load control panel.

**Comment by DeoThemes** [comment]
We have the same issue with our custom plugin that uses Select2 control. Tried to restart the server, clear cache, nothing works. The editor panel is empty and console show message: **ReferenceError: elementorDevTools is not defined**

**Comment by DeoThemes** [comment]
After some debugging we found out that this bug was related to the widgets registration hook, which should be:
`add_action( 'elementor/widgets/register', array( $this, 'register_widgets' ) );`

It only happens after 3.7 version. Hope this helps someone.
