### ISSUE TITLE
Uncaught TypeError: b.toLowerCase is not a function when click on Custom Tab on Section

### ISSUE THREAD

**Issue by frafish** [elementor/elementor#12348]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.
![custom-tab](https://user-images.githubusercontent.com/66823374/91696513-f99dff80-eb6f-11ea-8d5e-983546de1181.png)

## Description

New JS error in Editor with version 3.0.4 (it was working well on 3.0.1):
Uncaught TypeError: b.toLowerCase is not a function

![custom-tab](https://user-images.githubusercontent.com/66823374/91695823-02da9c80-eb6f-11ea-9e1e-6f596b455fd7.png)

## Steps to reproduce

You can reproduce it clicking on a Custom Tab on Sections (maybe which have a Repeater inside?!).

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.41 (Ubuntu)
	MySQL version: (Ubuntu) v8.0.21
	PHP Version: 7.4.7
	PHP Max Input Vars: 1000
	PHP Max Post Size: 800M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5.1-RC1-48902
	Site URL: http://localhost
	Home URL: http://localhost
	WP Multisite: No
	Max Upload Size: 200 MB
	Memory limit: 256M
	Permalink Structure: /blog/%postname%/
	Language: en-US
	Timezone: Europe/Rome
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0

== Active Plugins ==

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	e-addons for Elementor
		Version: 1.0.3
		Author: Nerds Farm

	Easy Digital Downloads
		Version: 2.9.24
		Author: Sandhills Development, LLC

	Elementor
		Version: 3.0.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.1
		Author: Elementor.com

	Pods - Custom Content Types and Fields
		Version: 2.7.22
		Author: Pods Framework Team

	Query Monitor
		Version: 3.6.4
		Author: John Blackbourn

	User Switching
		Version: 1.5.5
		Author: John Blackbourn & contributors

	WordPress Beta Tester
		Version: 2.2.12
		Author: Peter Westwood, Andy Fragen

== Log ==
	
PHP: showing 6 of 6
PHP: 2020-08-12 17:52:28 [notice X 5][/var/www/html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-12 19:55:48 [notice X 5][/var/www/html/wp-content/plugins/elementor/includes/managers/image.php::86] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-13 17:29:32 [error X 2][/var/www/html/wp-content/plugins/elementor/includes/controls/date-time.php::50] Uncaught Error: Class 'Elementor\TagsModule' not found in /var/www/html/wp-content/plugins/elementor/includes/controls/date-time.php:50
Stack trace:
#0 /var/www/html/wp-content/plugins/elementor/includes/controls/base.php(73): Elementor\Control_Date_Time->get_default_settings()
#1 /var/www/html/wp-content/plugins/elementor/includes/managers/controls.php(433): Elementor\Base_Control->__construct()
#2 /var/www/html/wp-content/plugins/elementor/includes/managers/controls.php(507): Elementor\Controls_Manager->register_controls()
#3 /var/www/html/wp-content/plugins/elementor/includes/managers/controls.php(526): Elementor\Controls_Manager->get_controls()
#4 /var/www/html/wp-content/plugins/elementor/includes/managers/controls.php(683): Elementor\Controls_Manager->get_control()
#5 /var/www/html/wp-content/plugins/elementor/includes/base/controls-stack.php(410): Elementor\Controls_Manager->add_control_to_stack()
#6 /var/www/html/wp-content/plugins/elementor/includes/base/controls-stack.php(1369): Elementor\Controls_S [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-25 12:09:52 [warning X 6][/var/www/html/wp-content/plugins/elementor/core/files/manager.php::121] unlink(/var/www/html/wp-content/uploads/elementor/css/min): Is a directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 4 of 4JS: 2020-08-13 08:39:06 [error X 4][http://localhost/wp-content/plugins/elementor/assets/js/editor-modules.js?ver=3.0.0-beta5:5368:9] globalControl is undefined 
JS: 2020-08-19 12:46:02 [error X 5][http://localhost/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp:4:11101] b.toLowerCase is not a function 
JS: 2020-08-24 08:06:09 [error X 4][http://localhost/wp-content/plugins/elementor/assets/js/editor.js?ver=3.0.0-beta6:10066:11] setting getter-only property \"children\" 
JS: 2020-08-25 19:38:49 [error X 7][http://localhost/wp-content/plugins/elementor/assets/js/editor.js?ver=3.0.1:22879:7] elementor.config.document is undefined 

Log: showing 20 of 322020-08-19 09:20:39 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-19 09:20:39 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.0-beta5',
  'to' => '3.0.0-beta6',
)]
2020-08-25 12:09:51 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.0-beta6',
  'to' => '3.0.0',
)]
2020-08-25 12:09:52 [info] elementor::elementor_updater Started 
2020-08-25 12:09:52 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-25 12:09:52 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-25 12:09:52 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-25 12:09:52 [notice] System colors already exist. nothing to do. 
2020-08-25 12:09:52 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-25 12:09:52 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-25 12:09:52 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-25 12:09:52 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-25 12:09:52 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-25 12:09:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.0-beta6',
  'to' => '3.0.0',
)]
2020-08-25 15:35:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.0-beta3',
  'to' => '3.0.0',
)]
2020-08-25 21:36:52 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.0',
  'to' => '3.0.1',
)]
2020-08-27 19:16:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.1',
  'to' => '3.0.2',
)]
2020-08-27 19:28:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.0',
  'to' => '3.0.1',
)]
2020-08-27 19:33:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.2',
  'to' => '3.0.3',
)]
2020-08-31 08:21:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.3',
  'to' => '3.0.4',
)]

				
</details>

**Comment by benbartels** [comment]
same problem after update here

**Comment by arielk** [comment]
Can you please update Elementor to the latest version, deactivate all other plugins also, and let me know if it solve you problem?

**Comment by frafish** [comment]
Bug is fixed.
Thanks
